apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - ./deployment.yaml
  - ./secret-provider-class.yaml
  - ./service-account.yaml
namespace: image-extraction-service
images:
  - name: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helix-dash
    newName: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helix-dash
    newTag: 0.1.1-b0790b3
  - name: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helixworlds-image-extraction-service
    newName: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helixworlds-image-extraction-service
    newTag: 0.2.181-5bdbafe
