apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: helixworlds-image-extraction-service-secrets
  namespace: image-extraction-service
spec:
  provider: aws
  secretObjects:
    - secretName: helixworlds-image-extraction-service-secrets
      type: Opaque
      data:
        - objectName: DatabaseUrl
          key: DATABASE_URL
        - objectName: AwsAccessKeyId
          key: AWS_ACCESS_KEY_ID
        - objectName: AwsSecretAccessKey
          key: AWS_SECRET_ACCESS_KEY
        - objectName: AuthClientId
          key: AUTH_CLIENT_ID
        - objectName: AuthClientSecret
          key: AUTH_CLIENT_SECRET
  parameters:
    objects: |
      - objectName: dev/helixworlds-image-extraction-service
        objectType: secretsmanager
        jmesPath:
        - path: "DATABASE_URL"
          objectAlias: "DatabaseUrl"
        - path: "AWS_ACCESS_KEY_ID"
          objectAlias: "AwsAccessKeyId"
        - path: "AWS_SECRET_ACCESS_KEY"
          objectAlias: "AwsSecretAccessKey"
        - path: "AUTH_CLIENT_ID"
          objectAlias: "AuthClientId"
        - path: "AWS_SECRET_ACCESS_KEY"
          objectAlias: "AwsSecretAccessKey"
        - path: "AWS_ACCESS_KEY_ID"
          objectAlias: "AwsAccessKeyId"
        - path: "AUTH_CLIENT_SECRET"
          objectAlias: "AuthClientSecret"
