apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 'image-extraction-service'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 'image-extraction-service'
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
