apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-image-extraction-service-secrets
  namespace: image-extraction-service
spec:
  provider: aws
  secretObjects:
    - secretName: myapp-image-extraction-service-secrets
      type: Opaque
      data:
        - objectName: DatabaseUrl
          key: DATABASE_URL
