apiVersion: v1
kind: Service
metadata:
  name: 'helixworlds-image-extraction-service'
  namespace: 'image-extraction-service'
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: 'image-extraction-service'
