apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - ./deployment.yaml
  - ./secret-provider-class.yaml
  - ./service-account.yaml
  - ./pod-autoscaler.yaml
namespace: gatherer
images:
  - name: 979222079345.dkr.ecr.us-east-1.amazonaws.com/coconft-api
    newName: 979222079345.dkr.ecr.us-east-1.amazonaws.com/coconft-api
  - name: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helix-dash
    newName: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helix-dash
    newTag: v0.0.1-22cfca64
  - name: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helixworlds-image-extraction-service
    newName: 979222079345.dkr.ecr.us-east-1.amazonaws.com/helixworlds-image-extraction-service
    newTag: 0.2.25-fb0a545
