name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Prisma Client
        run: |
          npx prisma generate

      - name: Set environment variables
        run: |
          echo "AWS_BUCKET_NAME=laineltestbucket" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          chmod +x script/unittest.sh
          ./script/unittest.sh